# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Lizhi Guo - PhD Candidate researching cognitive reserve, social determinants, and neuroimaging in aging populations at The Chinese University of Hong Kong.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Lizhi Guo'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Lizhi Guo. All Rights Reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
# Map Block
map:
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: Mapbox
  #   3: OpenStreetMap
  engine: 3
  # API key for your map provider (if required)
  # See https://docs.hugoblox.com/getting-started/hugo-basics/#edit-configuration
  api_key: ''
  # Map address for marker
  address:
    Email: 'guolz@cuhk.edu.hk'
    direction: 'Room 345, Department of Psychology'
    street: 'Sino Building, The Chinese University of Hong Kong'
    city: 'Shatin'
    region: 'NT'
    postcode: ''
    country: 'Hong Kong'
  # Location for map marker
  coordinates:
    latitude: '22.4150160580301'
    longitude: '114.20748207408691'
  # Map zoom level
  zoom: 16
